- name: Check existing GitHub Container Registry Docker proxy repo
  uri:
    url: "{{ nexus_base_url }}/service/rest/v1/repositories/{{ nexus_ghcr_proxy_repo }}"
    method: GET
    user: admin
    password: "{{ lookup('env', 'NEXUS_ADMIN_PASSWORD') }}"
    force_basic_auth: true
    status_code: [200, 404]
    timeout: 10
  register: nexus_ghcr_proxy_check
  no_log: true

- name: Create or update GitHub Container Registry Docker proxy repo
  uri:
    url: >-
      {{ nexus_base_url }}/service/rest/v1/repositories/docker/proxy{{ '/' + nexus_ghcr_proxy_repo if nexus_ghcr_proxy_check.status == 200 else '' }}
    method: "{{ 'PUT' if nexus_ghcr_proxy_check.status == 200 else 'POST' }}"
    user: admin
    password: "{{ lookup('env', 'NEXUS_ADMIN_PASSWORD') }}"
    force_basic_auth: true
    body_format: json
    body:
      name: "{{ nexus_ghcr_proxy_repo }}"
      online: true
      storage:
        blobStoreName: "{{ nexus_blob_store }}"
        strictContentTypeValidation: true
      proxy:
        remoteUrl: "{{ nexus_ghcr_remote_url }}"
        contentMaxAge: 1440
        metadataMaxAge: 1440
      negativeCache:
        enabled: true
        timeToLive: 1440
      httpClient:
        blocked: false
        autoBlock: true
        connection:
          retries: 2
          timeout: 300
      docker:
        v1Enabled: false
        forceBasicAuth: true
      dockerProxy:
        indexType: REGISTRY
        indexUrl: "{{ nexus_ghcr_remote_index_url }}"
    status_code: [200, 201, 204]
    timeout: 30
  no_log: true
